In [71]:
import pandas as pd

In [72]:
df_pops = pd.read_csv('merged.ind', delim_whitespace=True, names = ['name', 'sex', 'pop'])
pops_list = list(pd.read_csv('pops_list', header=None)[0])

In [73]:
pops_list

['Abkhasian.HO',
 'Adygei.HO',
 'Albanian.HO',
 'Algerian.HO',
 'Armenian.HO',
 'Assyrian.HO',
 'Balkar.HO',
 'Basque.HO',
 'BedouinA.HO',
 'BedouinB.HO',
 'Belarusian.HO',
 'Bulgarian.HO',
 'Chechen.HO',
 'Croatian.HO',
 'Cypriot.HO',
 'Czech.HO',
 'Druze.HO',
 'English.HO',
 'Estonian.HO',
 'Finnish.HO',
 'French.HO',
 'Georgian.HO',
 'Hungarian.HO',
 'Icelandic.HO',
 'Iran_Zoroastrian.HO',
 'Iranian.HO',
 'Italian_North.HO',
 'Italian_South.HO',
 'Jew_Ashkenazi.HO',
 'Jew_Georgian.HO',
 'Jew_Iranian.HO',
 'Jew_Iraqi.HO',
 'Jew_Libyan.HO',
 'Jew_Moroccan.HO',
 'Jew_Tunisian.HO',
 'Jew_Turkish.HO',
 'Jew_Yemenite.HO',
 'Jordanian.HO',
 'Kumyk.HO',
 'Lebanese.HO',
 'Lebanese_Christian.HO',
 'Lebanese_Muslim.HO',
 'Lezgin.HO',
 'Libyan.HO',
 'Lithuanian.HO',
 'Maltese.HO',
 'Mordovian.HO',
 'Moroccan.HO',
 'Norwegian.HO',
 'Orcadian.HO',
 'Ossetian.HO',
 'Palestinian.HO',
 'Romanian.HO',
 'Russian.HO',
 'Sardinian.HO',
 'Saudi.HO',
 'Scottish.HO',
 'Sicilian.HO',
 'Spanish.HO',
 'Spanish_North.HO',
 'Syrian.HO',
 'Tunisian.HO',
 'Turkish.HO',
 'Ukrainian.HO',
 'Egyptian.HO']

In [78]:
to_remove = ['Basque.HO', 'Scottish.HO', 'Sicilian.HO', 'Spanish.HO', 'Spanish_North.HO','Icelandic.HO', 'Ukrainian.HO','Romanian.HO','Russian.HO', 'English.HO',
 'Estonian.HO','Finnish.HO','French.HO', 'Belarusian.HO','Bulgarian.HO', 'Mordovian.HO', 'Sardinian.HO', 'Adygei.HO', 'Czech.HO', 'Croatian.HO', 'Lithuanian.HO', 
            'Italian_North.HO', 'Hungarian.HO', 'Norwegian.HO', 'Balkar.HO', 'Georgian.HO', 'Orcadian.HO', 'Chechen.HO', 'Ossetian.HO', 'Cypriot.HO', 'Lezgin.HO',
            'Albanian.HO', 'Abkhasian.HO', 'Adygei.HO', 'Albanian.HO','Armenian.HO', 'Assyrian.HO','Kumyk.HO',]
pops_list = [pop for pop in pops_list if pop not in to_remove]
pops_list = pops_list + ['Unknown']

In [91]:
df_pops[df_pops['pop'].isin(pops_list)].loc[:, ['pop']].iloc[:,0].unique()

array(['Unknown', 'Iran_Zoroastrian.HO', 'Druze.HO', 'BedouinB.HO',
       'BedouinA.HO', 'Palestinian.HO', 'Iranian.HO', 'Syrian.HO',
       'Lebanese.HO', 'Jordanian.HO', 'Saudi.HO', 'Egyptian.HO',
       'Jew_Libyan.HO', 'Maltese.HO', 'Tunisian.HO', 'Jew_Ashkenazi.HO',
       'Jew_Turkish.HO', 'Jew_Tunisian.HO', 'Italian_South.HO',
       'Algerian.HO', 'Jew_Yemenite.HO', 'Turkish.HO', 'Jew_Iranian.HO',
       'Jew_Iraqi.HO', 'Jew_Moroccan.HO', 'Jew_Georgian.HO',
       'Lebanese_Christian.HO', 'Lebanese_Muslim.HO', 'Libyan.HO',
       'Moroccan.HO'], dtype=object)

In [92]:
df_pops[df_pops['pop'].isin(pops_list)].loc[:, ['name']].to_csv('iids_to_keep', index = None, header = None, sep = '\t')

In [76]:
df_pops.loc[:, ['name']]#.to_csv('iids_to_keep', index = None, header = None, sep = '\t')

                            name
0                          JD206
1                        I001.HO
2                        I002.HO
3                   IREJ-T006.HO
4                   IREJ-T009.HO
...                          ...
20499       I19456_v54.1_addback
20500  S1944.E1.L3_v54.1_addback
20501  S1951.E1.L3_v54.1_addback
20502  S7241.E1.L1_v54.1_addback
20503        I1877_v54.1_addback

[20504 rows x 1 columns]

In [70]:
import pandas as pd
fam   = pd.read_csv("merged_pruned_subset.fam", delim_whitespace=True, header=None)
meta  = pd.read_csv("pop_labels.tsv", sep='\t', names=['IID','Pop'])   # your label file
ind   = fam[[1,4]].rename(columns={1:'IID',4:'Sex'}).merge(meta, on='IID')
ind['Sex'] = ind['Sex'].replace({1:'M',2:'F',0:'U'})   # EIGENSTRAT codes
ind[['IID','Sex','Pop']].to_csv('merged_pruned_subset.ind', sep='\t', index=False, header=False)

FileNotFoundError: [Errno 2] No such file or directory: 'pop_labels.tsv'

In [94]:
pops = pd.read_csv('merged_pruned_subset_keep.fam')

In [95]:
pops

           1 JD206 0 0 0 1
0      55 SH001.HO 0 0 1 1
1      56 SH003.HO 0 0 1 1
2      57 SH004.HO 0 0 1 1
3      58 SH005.HO 0 0 1 1
4      59 SH007.HO 0 0 1 1
..                     ...
404  3616 PV034.HO 0 0 1 1
405  3617 PV035.HO 0 0 1 1
406  3618 PV036.HO 0 0 1 1
407  3619 PV037.HO 0 0 1 1
408  3620 PV038.HO 0 0 1 1

[409 rows x 1 columns]